### ISSUE TITLE
Lexical match metadata

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#151]
Currently we include preprocessing and match fields for lexical matches, but there are other things to consider like:

- edit distance (threshold based, like semantic similarity, some kind of `lexical_similarity_score`. Maybe generalise the semantic similarity score we already have to `similarity_score?

**Comment by jonquet** [comment]
The problem is that mapping tool are often made of a bunch of components and very often include a "lexical matcher" and "a semantic similarity measure" too. The score obtained by each of these "components" are only significant if normalized and in the case the tool is only made of one component. => I mean if the score of the component does actually represent the score of the mapping. 

I would in fact propose two properties  "mapping_score" and "mapping_normalized_score"  that would typically be the score (aggregated by the mapping tool) and also normalized [0-100]. If not normalized, these score are hardly re-usable in multiple mappings contexts.

**Comment by matentzn** [comment]
What you are saying makes total sense, but do you really believe that recording an unnormalised score is useful at all? My feeling was to assume all scores to be normalised..

**Comment by jonquet** [comment]
I sort of agree with this too...

**Comment by matentzn** [comment]
I will close this issue as not actionable, concrete feature requests will be dealt with separately.
