### ISSUE TITLE
Add tutorial on how to pick the right mapping predicate

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#176]
It is frequently confusing to people to see mapping predicates like 
- skos:closeMatch and oboInOwl:hasDbXref
- skos:exactMatch and owl:equivalentClass

side by side. Beyond the [spec](https://mapping-commons.github.io/sssom/spec/#common-mapping-predicates) we should provide a better guide on selecting the appropriate mapping predicate for every case.

**Comment by cmungall** [comment]
One perspective that should be covered is mappings for an ontology with many annotations that needs to propagate annotations from other systems

here mappings are implicitly exact or narrow from the perspective of the resource, otherwise propagation is invalid . Think ec2go interpro2go etc. the predicate is implicitly in the name. but people get confused using the mappings for other purposes. 

I think using pragmatic examples like this could help future docs

**Comment by matentzn** [comment]
Sounds great, I think we should probably discuss this a bit in one of our next calls, I put in on the agenda.

**Comment by matentzn** [comment]
A good first draft is provided here: https://mapping-commons.github.io/sssom/mapping-predicates/ closing for more concrete issues.
