### ISSUE TITLE
File mapping rules metadata idea

### ISSUE THREAD

**Issue by mellybelly** [mapping-commons/SSSOM#31]
Starting a thread on how we might create a metadata structure for the rules used for the mapping. This would be for the whole file and could go in the header. It would require consideration of the mapping type field since you will often have more than one mapping type for a given mapping. For example, if I only make exact mappings when there is both a lexical match as well as on a synonym, or logical def, or Xref, etc.

There should be a "rule" for each type of mapping present in the file.  Maybe start with somethign like:

| predicate_id	| include_match_type | exclude_match_type	
| --- | --- | --- | 
| skos:exactMatch | Lexical; Logical |   |
| skos:narrowMatch | Synonym | Lexical |

other more complex examples of inclusion/exclusion criteria - exact string match on definition string, matching both primary label and at least one synonym and not matching synonyms on other terms, use of dbxrefs, etc.

**Comment by matentzn** [comment]
What you call `include_match_type` seems like what we intended the (mandatory) `match_type` field to be. I think it can make sense to allow multiple match types per mapping, so consider this done.  To understand the `exclude_match_type` i need some convincing use case; there is always an infinite number of match types that are excluded from the match; namely all the ones that were not tested. For the tested and did not find I prefer the discussion in #28. 

I think the way you conceptualise this in your mind is that we provide these mapping rules on the level of the mapping set, basically saying something like: "in order to determine skos:exactMatch, we required a lexical match or a logical match". The way SSSOM is structured we would rather say this on the level of the individual matches (the A--[skos:exactMatch]-->B map was determined through a Lexical or a Logical Match, the current `match_type`).

**Comment by mellybelly** [comment]
I will come up with some good examples for both. In the meantime, I guess I would still have to pass a set of rules used to create the mappings along with the rows? How else would I know all mappings that are included in the file were all of the possible mappings that met the same requirements for the mapping? 

I need to know at the file level what the curation rules were in order to determine whether or not to use someone else's mapping file (and/or what to remove if I didn't want to include something).

**Comment by matentzn** [comment]
Hahah we will have to discuss this in a meeting. I see you are coming from some kind of "closed world" perspective, whereas my main use case was to mix and match mappings aggregated from many different sources effectively.. Thats why I kind of did not consider global mapping set curation rules too much -> the moment I want to use them (say for constructing a knowledge graph), I really only look at the level of the individual mappings. Lets gather some more tickets and then make this the main topic of a Monarch Data call.

**Comment by matentzn** [comment]
Closing this in favour of #57
