### ISSUE TITLE
Decide on a canonical date format: xsd:date vs xsd:dateTime

### ISSUE THREAD

**Issue by sbello** [mapping-commons/sssom#67]
I'm trying to put together a template for creating mappings. Is there a recommended format for the date?

Also is there any additional information you would consider essential for a template other than what I already have in this?

https://docs.google.com/spreadsheets/d/1e0hm_WNlzP-kUJHC54LU1W_gwUMVXvDv1kZfGAaMcGI/edit?usp=sharing

**Comment by matentzn** [comment]
Thank you @sbello 

These are the two datatype we are considering:
https://www.w3schools.com/xml/schema_dtypes_date.asp

- 👍 xsd:date is very simple and probably sufficient for mappings, e.g. `2002-09-24`
- 🚀 xsd:dateTime is more granular, and probably more popular in the semantic web `2002-05-30T09:00:00`

I personally for now will vote for `xsd:date` because I like its simplicity; I trust more @cthoyt, @graybeal, @cmungall and @jamesaoverton though and may change my mind. In any case, you can go aheave an use either one for now and convert it later! Thank you for the ticket :)

For the minimum metadata see #69 - we will continue the convo there.

**Comment by AlasdairGray** [comment]
I would suggest using `xsd:date`.

In the Open PHACTS dataset descriptions we recommended the use of `xsd:datetime` because that was the type specified in the Provenance, Versioning, and Authoring ([PAV](https://pav-ontology.github.io/pav/)) ontology for the properties that we were using. However, most data providers only provided `xsd:date`.

**Comment by matentzn** [comment]
Thank you @AlasdairGray you can cast your vote in the issue above but adding the thumbs up!

**Comment by AlasdairGray** [comment]
The text is ambiguous as there are two options outlined, which is why I wrote my comment. So a thumbs up means that you are in favour of `xsd:date`?

Also the comment gives further insight and evidence to support the position.

**Comment by matentzn** [comment]
Yes, we use this a lot now across obo. We assign emoticons to options, then we vote. You can even vote for multiple options - and your additional comments will be read by anyone looking to cast a vote to influence their opinion, so that's great!

**Comment by matentzn** [comment]
An yes, thumbs up mean you prefer dad date!

**Comment by sbello** [comment]
Thanks Nico! xsd:date makes sense, xsd:dateTime is way to granular.

**Comment by graybeal** [comment]
As always, depends on the applications. A main purpose of this information is to determine (after the fact) order of inputs/operations. If you have a group of 10 people developing mappings in a day, and you are trying to determine which mappings preceded/followed which other mappings (example use cases: which mappings got included in version X? when mapping Y was created could the user already see mapping Z? was the key person there when this mapping was created? when was the system or process most busy?), you have to have the timestamps to do that. That's why any computer event logging application will use datetime.  (Using datetime also make more interesting meta-analyses possible, but I'm sure that's not of keen interest to the average end user!)

That said, I know it's a huge pain to manage that information manually, so if you're going to make a human being provide lots of their own timestamps (can't there be an Excel function to auto-fill this somehow?), I can't expect meaningful datetimes.

But call this a place to thumbs-up the date-time option.

**Comment by matentzn** [comment]
Hey @graybeal:

Just because I think this voting mechanism should be more prevalent everywhere: You should cast your vote directly on the `VOTE` [comment above](https://github.com/mapping-commons/SSSOM/issues/67#issuecomment-881287243). Thank you for your insights!

**Comment by graybeal** [comment]
Oops, sorry, got it!

**Comment by cthoyt** [comment]
I'm not super opinionated about this. I think date might be easier to deal with just because it's also more human-friendly. I'm not sure if there are any really specific scenarios where the time of day or specific ordering is important. However, if these will all be added automatically, there's no reason not to use the more granular one.

**Comment by matentzn** [comment]
xsd:date it is!
